[project]
name = "api-one"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.5",
    "scalar-fastapi>=1.0.3",
]

[dependency-groups]
dev = [
    "ruff>=0.7.4",
]
